name: Astro

on: [push]

env:
  AZURE_WEBAPP_NAME: GitHubAction
  AZURE_WEBAPP_PACKAGE_PATH: './published' 
  NETCORE_VERSION: '5.0.x'     # set this to the path to your web app project, defaults to the repository root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: publish app for deploy
        run: dotnet publish --configuration Release --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: 'Astro'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      - name: Test
        run: dotnet test --no-restore --verbosity normal

     